apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  namespace: eqns2
  labels:
    app: nginx-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx-2
        image: nginx
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
