apiVersion: v1
kind: Namespace
metadata:
  name: eqns2
  labels:
    name: eqns2
---
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: equota2
  namespace: eqns2
spec:
  min:
    nvidia.com/gpu: 1
  max:
    nvidia.com/gpu: 3
